<?php
$functionLayout->homeslider();
$DanhSacDanhMuc = $functionLayout->GetConfigByKey(theme\gocvoi\functionLayout::DanMucSanPham);
$SanPham = new \Model\Products();
$DS = $SanPham->ProductsAllPT(1, 12, $tong);

if ($DanhSacDanhMuc) {
    foreach ($DanhSacDanhMuc as $k => $danhmuc) {
        $cat = new \Model\Category($danhmuc["DanhMuc"]);
        $DanhSachSanPham = $cat->GetProducts();
        ?>
        <div class="products-best-selling module">
            <div class="container">
                <h2 class="module-title wow fadeInDown"><?php echo $cat->catName; ?></h2>
                <div class="module-content products-promotion-list product-list">
                    <div class="row ListProduct">
                        <?php
                        if ($DanhSachSanPham) {
                            foreach ($DanhSachSanPham as $pro) {
                                $_pro = new \Model\Products($pro);
                                ?>
                                <div class="col-sm-6 col-md-3 col-lg-2 product-item wow fadeInUp">
                                    <?php
                                    if ($_pro->isShow == \Model\Products::News) {
                                        ?>
                                        <img class="icon-new" src="/public/news.png" alt=""/>
                                        <?php
                                    }
                                    ?>
                                    <div class="product-item-image">
                                        <figure>
                                            <a href="<?php echo $_pro->linkProduct() ?>">
                                                <img class="hinhVuong" src="<?php echo $_pro->UrlHinh() ?>" alt="<?php echo $_pro->nameProduct ?>">
                                            </a>
                                            <?php
                                            if ($_pro->Number == 0) {
                                                ?>
                                                <span class="product-out-store">Hết Hàng</span>
                                                <?php
                                            }
                                            ?>
                                        </figure>
                                        <?php
                                        if ($_pro->oldPrice > 0) {
                                            ?>
                                            <span class="product-item-label"><?php echo $_pro->GiamGia(); ?>%</span>
                                            <?php
                                        }
                                        ?>
                                    </div>
                                    <h3 class="product-item-title">
                                        <a href="<?php echo $_pro->linkProduct() ?>"><?php echo $_pro->nameProduct ?></a>
                                    </h3>
                                    <div class="product-item-price">
                                        <?php
                                        if ($_pro->oldPrice > 0) {
                                            ?>
                                            <del><?php echo $_pro->oldPrice ?></del>
                                            <?php
                                        }
                                        ?>
                                        <ins><?php echo $_pro->Price(); ?></ins>
                                    </div>
                                    <div class="product-item-view readmore">
                                        <?php
                                        $_pro->btnGioHang();
                                        ?>

                                    </div>
                                </div>
                                <?php
                            }
                        }
                        ?>

                    </div>
                </div>
            </div>
        </div>
        <?php
    }
}
?>

