<form action="" method="POST" enctype="multipart/form-data" > 
            
                <div class="form-group">
                <label for="">__ID___</label>
                <input type="text" value="{{\classdatabase\bakcoadv.ID}}" class="form-control" name="ID" >
            </div>
            
                <div class="form-group">
                <label for="">__Name___</label>
                <input type="text" value="{{\classdatabase\bakcoadv.Name}}" class="form-control" name="Name" >
            </div>
            
                <div class="form-group">
                <label for="">__Content___</label>
                <input type="text" value="{{\classdatabase\bakcoadv.Content}}" class="form-control" name="Content" >
            </div>
            
                <div class="form-group">
                <label for="">__Attribute___</label>
                <input type="text" value="{{\classdatabase\bakcoadv.Attribute}}" class="form-control" name="Attribute" >
            </div>
            
                <div class="form-group">
                <label for="">__DataAttribute___</label>
                <input type="text" value="{{\classdatabase\bakcoadv.DataAttribute}}" class="form-control" name="DataAttribute" >
            </div>
            
                <div class="form-group">
                <label for="">__Group___</label>
                <input type="text" value="{{\classdatabase\bakcoadv.Group}}" class="form-control" name="Group" >
            </div>
            
                <div class="form-group">
                <label for="">__Urlimages___</label>
                <input type="text" value="{{\classdatabase\bakcoadv.Urlimages}}" class="form-control" name="Urlimages" >
            </div>
            
                <div class="form-group">
                <label for="">__Link___</label>
                <input type="text" value="{{\classdatabase\bakcoadv.Link}}" class="form-control" name="Link" >
            </div>
            
                <div class="form-group">
                <label for="">__isShow___</label>
                <input type="text" value="{{\classdatabase\bakcoadv.isShow}}" class="form-control" name="isShow" >
            </div>
            
                <div class="form-group">
                <label for="">__createDate___</label>
                <input type="text" value="{{\classdatabase\bakcoadv.createDate}}" class="form-control" name="createDate" >
            </div>
            
                <div class="form-group">
                <label for="">__updateDate___</label>
                <input type="text" value="{{\classdatabase\bakcoadv.updateDate}}" class="form-control" name="updateDate" >
            </div>
            
            </form>