<form action="" method="POST" enctype="multipart/form-data" > 
            
                <div class="form-group">
                <label for="">__ID___</label>
                <input type="text" value="{{\classdatabase\bakcoproduct.ID}}" class="form-control" name="ID" >
            </div>
            
                <div class="form-group">
                <label for="">__Username___</label>
                <input type="text" value="{{\classdatabase\bakcoproduct.Username}}" class="form-control" name="Username" >
            </div>
            
                <div class="form-group">
                <label for="">__catID___</label>
                <input type="text" value="{{\classdatabase\bakcoproduct.catID}}" class="form-control" name="catID" >
            </div>
            
                <div class="form-group">
                <label for="">__nameProduct___</label>
                <input type="text" value="{{\classdatabase\bakcoproduct.nameProduct}}" class="form-control" name="nameProduct" >
            </div>
            
                <div class="form-group">
                <label for="">__Alias___</label>
                <input type="text" value="{{\classdatabase\bakcoproduct.Alias}}" class="form-control" name="Alias" >
            </div>
            
                <div class="form-group">
                <label for="">__Price___</label>
                <input type="text" value="{{\classdatabase\bakcoproduct.Price}}" class="form-control" name="Price" >
            </div>
            
                <div class="form-group">
                <label for="">__oldPrice___</label>
                <input type="text" value="{{\classdatabase\bakcoproduct.oldPrice}}" class="form-control" name="oldPrice" >
            </div>
            
                <div class="form-group">
                <label for="">__Summary___</label>
                <input type="text" value="{{\classdatabase\bakcoproduct.Summary}}" class="form-control" name="Summary" >
            </div>
            
                <div class="form-group">
                <label for="">__Content___</label>
                <input type="text" value="{{\classdatabase\bakcoproduct.Content}}" class="form-control" name="Content" >
            </div>
            
                <div class="form-group">
                <label for="">__UrlHinh___</label>
                <input type="text" value="{{\classdatabase\bakcoproduct.UrlHinh}}" class="form-control" name="UrlHinh" >
            </div>
            
                <div class="form-group">
                <label for="">__DateCreate___</label>
                <input type="text" value="{{\classdatabase\bakcoproduct.DateCreate}}" class="form-control" name="DateCreate" >
            </div>
            
                <div class="form-group">
                <label for="">__Number___</label>
                <input type="text" value="{{\classdatabase\bakcoproduct.Number}}" class="form-control" name="Number" >
            </div>
            
                <div class="form-group">
                <label for="">__Note___</label>
                <input type="text" value="{{\classdatabase\bakcoproduct.Note}}" class="form-control" name="Note" >
            </div>
            
                <div class="form-group">
                <label for="">__BuyTimes___</label>
                <input type="text" value="{{\classdatabase\bakcoproduct.BuyTimes}}" class="form-control" name="BuyTimes" >
            </div>
            
                <div class="form-group">
                <label for="">__Views___</label>
                <input type="text" value="{{\classdatabase\bakcoproduct.Views}}" class="form-control" name="Views" >
            </div>
            
                <div class="form-group">
                <label for="">__isShow___</label>
                <input type="text" value="{{\classdatabase\bakcoproduct.isShow}}" class="form-control" name="isShow" >
            </div>
            
                <div class="form-group">
                <label for="">__Serial___</label>
                <input type="text" value="{{\classdatabase\bakcoproduct.Serial}}" class="form-control" name="Serial" >
            </div>
            
                <div class="form-group">
                <label for="">__lang___</label>
                <input type="text" value="{{\classdatabase\bakcoproduct.lang}}" class="form-control" name="lang" >
            </div>
            
            </form>