<form action="" method="POST" enctype="multipart/form-data" > 
            
                <div class="form-group">
                <label for="">__catID___</label>
                <input type="text" value="{{\classdatabase\bakcocategories.catID}}" class="form-control" name="catID" >
            </div>
            
                <div class="form-group">
                <label for="">__catName___</label>
                <input type="text" value="{{\classdatabase\bakcocategories.catName}}" class="form-control" name="catName" >
            </div>
            
                <div class="form-group">
                <label for="">__Path___</label>
                <input type="text" value="{{\classdatabase\bakcocategories.Path}}" class="form-control" name="Path" >
            </div>
            
                <div class="form-group">
                <label for="">__Link___</label>
                <input type="text" value="{{\classdatabase\bakcocategories.Link}}" class="form-control" name="Link" >
            </div>
            
                <div class="form-group">
                <label for="">__Note___</label>
                <input type="text" value="{{\classdatabase\bakcocategories.Note}}" class="form-control" name="Note" >
            </div>
            
                <div class="form-group">
                <label for="">__parentCatID___</label>
                <input type="text" value="{{\classdatabase\bakcocategories.parentCatID}}" class="form-control" name="parentCatID" >
            </div>
            
                <div class="form-group">
                <label for="">__banner___</label>
                <input type="text" value="{{\classdatabase\bakcocategories.banner}}" class="form-control" name="banner" >
            </div>
            
                <div class="form-group">
                <label for="">__Public___</label>
                <input type="text" value="{{\classdatabase\bakcocategories.Public}}" class="form-control" name="Public" >
            </div>
            
                <div class="form-group">
                <label for="">__Serial___</label>
                <input type="text" value="{{\classdatabase\bakcocategories.Serial}}" class="form-control" name="Serial" >
            </div>
            
                <div class="form-group">
                <label for="">__Lang___</label>
                <input type="text" value="{{\classdatabase\bakcocategories.Lang}}" class="form-control" name="Lang" >
            </div>
            
            </form>