<form action="" method="POST" enctype="multipart/form-data" > 
            
                <div class="form-group">
                <label for="">__Id___</label>
                <input type="text" value="{{\classdatabase\bakcomenu.Id}}" class="form-control" name="Id" >
            </div>
            
                <div class="form-group">
                <label for="">__Name___</label>
                <input type="text" value="{{\classdatabase\bakcomenu.Name}}" class="form-control" name="Name" >
            </div>
            
                <div class="form-group">
                <label for="">__Link___</label>
                <input type="text" value="{{\classdatabase\bakcomenu.Link}}" class="form-control" name="Link" >
            </div>
            
                <div class="form-group">
                <label for="">__Parent___</label>
                <input type="text" value="{{\classdatabase\bakcomenu.Parent}}" class="form-control" name="Parent" >
            </div>
            
                <div class="form-group">
                <label for="">__Groups___</label>
                <input type="text" value="{{\classdatabase\bakcomenu.Groups}}" class="form-control" name="Groups" >
            </div>
            
                <div class="form-group">
                <label for="">__OrderBy___</label>
                <input type="text" value="{{\classdatabase\bakcomenu.OrderBy}}" class="form-control" name="OrderBy" >
            </div>
            
                <div class="form-group">
                <label for="">__Note___</label>
                <input type="text" value="{{\classdatabase\bakcomenu.Note}}" class="form-control" name="Note" >
            </div>
            
                <div class="form-group">
                <label for="">__createDate___</label>
                <input type="text" value="{{\classdatabase\bakcomenu.createDate}}" class="form-control" name="createDate" >
            </div>
            
                <div class="form-group">
                <label for="">__UpdateDate___</label>
                <input type="text" value="{{\classdatabase\bakcomenu.UpdateDate}}" class="form-control" name="UpdateDate" >
            </div>
            
            </form>