<form action="" method="POST" enctype="multipart/form-data" > 

    <div class="form-group">
        <label for="">__ID___</label>
        <input type="text" value="{{\classdatabase\bakconews.ID}}" class="form-control" name="ID" >
    </div>

    <div class="form-group">
        <label for="">__PageID___</label>
        <input type="text" value="{{\classdatabase\bakconews.PageID}}" class="form-control" name="PageID" >
    </div>

    <div class="form-group">
        <label for="">__Name___</label>
        <input type="text" value="{{\classdatabase\bakconews.Name}}" class="form-control" name="Name" >
    </div>

    <div class="form-group">
        <label for="">__Alias___</label>
        <input type="text" value="{{\classdatabase\bakconews.Alias}}" class="form-control" name="Alias" >
    </div>

    <div class="form-group">
        <label for="">__Summary___</label>
        <input type="text" value="{{\classdatabase\bakconews.Summary}}" class="form-control" name="Summary" >
    </div>

    <div class="form-group">
        <label for="">__Content___</label>
        <input type="text" value="{{\classdatabase\bakconews.Content}}" class="form-control" name="Content" >
    </div>

    <div class="form-group">
        <label for="">__title___</label>
        <input type="text" value="{{\classdatabase\bakconews.title}}" class="form-control" name="title" >
    </div>

    <div class="form-group">
        <label for="">__keyword___</label>
        <input type="text" value="{{\classdatabase\bakconews.keyword}}" class="form-control" name="keyword" >
    </div>

    <div class="form-group">
        <label for="">__description___</label>
        <input type="text" value="{{\classdatabase\bakconews.description}}" class="form-control" name="description" >
    </div>

    <div class="form-group">
        <label for="">__AnHien___</label>
        <input type="text" value="{{\classdatabase\bakconews.AnHien}}" class="form-control" name="AnHien" >
    </div>

    <div class="form-group">
        <label for="">__NgayDang___</label>
        <input type="text" value="{{\classdatabase\bakconews.NgayDang}}" class="form-control" name="NgayDang" >
    </div>

    <div class="form-group">
        <label for="">__UrlHinh___</label>
        <input type="text" value="{{\classdatabase\bakconews.UrlHinh}}" class="form-control" name="UrlHinh" >
    </div>

    <div class="form-group">
        <label for="">__TinNoiBat___</label>
        <input type="text" value="{{\classdatabase\bakconews.TinNoiBat}}" class="form-control" name="TinNoiBat" >
    </div>

    <div class="form-group">
        <label for="">__SoLanXem___</label>
        <input type="text" value="{{\classdatabase\bakconews.SoLanXem}}" class="form-control" name="SoLanXem" >
    </div>

    <div class="form-group">
        <label for="">__Stt___</label>
        <input type="text" value="{{\classdatabase\bakconews.Stt}}" class="form-control" name="Stt" >
    </div>

</form>