<form action="" method="POST" enctype="multipart/form-data" > 
            
                <div class="form-group">
                <label for="">__Username___</label>
                <input type="text" value="{{\classdatabase\bakcoadmin.Username}}" class="form-control" name="Username" >
            </div>
            
                <div class="form-group">
                <label for="">__Password___</label>
                <input type="text" value="{{\classdatabase\bakcoadmin.Password}}" class="form-control" name="Password" >
            </div>
            
                <div class="form-group">
                <label for="">__Random___</label>
                <input type="text" value="{{\classdatabase\bakcoadmin.Random}}" class="form-control" name="Random" >
            </div>
            
                <div class="form-group">
                <label for="">__Name___</label>
                <input type="text" value="{{\classdatabase\bakcoadmin.Name}}" class="form-control" name="Name" >
            </div>
            
                <div class="form-group">
                <label for="">__Email___</label>
                <input type="text" value="{{\classdatabase\bakcoadmin.Email}}" class="form-control" name="Email" >
            </div>
            
                <div class="form-group">
                <label for="">__Phone___</label>
                <input type="text" value="{{\classdatabase\bakcoadmin.Phone}}" class="form-control" name="Phone" >
            </div>
            
                <div class="form-group">
                <label for="">__Address___</label>
                <input type="text" value="{{\classdatabase\bakcoadmin.Address}}" class="form-control" name="Address" >
            </div>
            
                <div class="form-group">
                <label for="">__Note___</label>
                <input type="text" value="{{\classdatabase\bakcoadmin.Note}}" class="form-control" name="Note" >
            </div>
            
                <div class="form-group">
                <label for="">__Groups___</label>
                <input type="text" value="{{\classdatabase\bakcoadmin.Groups}}" class="form-control" name="Groups" >
            </div>
            
                <div class="form-group">
                <label for="">__Urrlimages___</label>
                <input type="text" value="{{\classdatabase\bakcoadmin.Urrlimages}}" class="form-control" name="Urrlimages" >
            </div>
            
            </form>