<form action="" method="POST" enctype="multipart/form-data" > 
            
                <div class="form-group">
                <label for="">__idPa___</label>
                <input type="text" value="{{\classdatabase\bakcopages.idPa}}" class="form-control" name="idPa" >
            </div>
            
                <div class="form-group">
                <label for="">__idGroup___</label>
                <input type="text" value="{{\classdatabase\bakcopages.idGroup}}" class="form-control" name="idGroup" >
            </div>
            
                <div class="form-group">
                <label for="">__Name___</label>
                <input type="text" value="{{\classdatabase\bakcopages.Name}}" class="form-control" name="Name" >
            </div>
            
                <div class="form-group">
                <label for="">__Alias___</label>
                <input type="text" value="{{\classdatabase\bakcopages.Alias}}" class="form-control" name="Alias" >
            </div>
            
                <div class="form-group">
                <label for="">__Title___</label>
                <input type="text" value="{{\classdatabase\bakcopages.Title}}" class="form-control" name="Title" >
            </div>
            
                <div class="form-group">
                <label for="">__Des___</label>
                <input type="text" value="{{\classdatabase\bakcopages.Des}}" class="form-control" name="Des" >
            </div>
            
                <div class="form-group">
                <label for="">__Keyword___</label>
                <input type="text" value="{{\classdatabase\bakcopages.Keyword}}" class="form-control" name="Keyword" >
            </div>
            
                <div class="form-group">
                <label for="">__Summary___</label>
                <input type="text" value="{{\classdatabase\bakcopages.Summary}}" class="form-control" name="Summary" >
            </div>
            
                <div class="form-group">
                <label for="">__Content___</label>
                <input type="text" value="{{\classdatabase\bakcopages.Content}}" class="form-control" name="Content" >
            </div>
            
                <div class="form-group">
                <label for="">__Urlimages___</label>
                <input type="text" value="{{\classdatabase\bakcopages.Urlimages}}" class="form-control" name="Urlimages" >
            </div>
            
                <div class="form-group">
                <label for="">__isShow___</label>
                <input type="text" value="{{\classdatabase\bakcopages.isShow}}" class="form-control" name="isShow" >
            </div>
            
                <div class="form-group">
                <label for="">__Type___</label>
                <input type="text" value="{{\classdatabase\bakcopages.Type}}" class="form-control" name="Type" >
            </div>
            
                <div class="form-group">
                <label for="">__Note___</label>
                <input type="text" value="{{\classdatabase\bakcopages.Note}}" class="form-control" name="Note" >
            </div>
            
            </form>