<form action="" method="POST" enctype="multipart/form-data" > 
            
                <div class="form-group">
                <label for="">__idPa___</label>
                <input type="text" value="{{\Model\pages.idPa}}" class="form-control" name="idPa" >
            </div>
            
                <div class="form-group">
                <label for="">__idGroup___</label>
                <input type="text" value="{{\Model\pages.idGroup}}" class="form-control" name="idGroup" >
            </div>
            
                <div class="form-group">
                <label for="">__Name___</label>
                <input type="text" value="{{\Model\pages.Name}}" class="form-control" name="Name" >
            </div>
            
                <div class="form-group">
                <label for="">__Alias___</label>
                <input type="text" value="{{\Model\pages.Alias}}" class="form-control" name="Alias" >
            </div>
            
                <div class="form-group">
                <label for="">__Title___</label>
                <input type="text" value="{{\Model\pages.Title}}" class="form-control" name="Title" >
            </div>
            
                <div class="form-group">
                <label for="">__Des___</label>
                <input type="text" value="{{\Model\pages.Des}}" class="form-control" name="Des" >
            </div>
            
                <div class="form-group">
                <label for="">__Keyword___</label>
                <input type="text" value="{{\Model\pages.Keyword}}" class="form-control" name="Keyword" >
            </div>
            
                <div class="form-group">
                <label for="">__Summary___</label>
                <input type="text" value="{{\Model\pages.Summary}}" class="form-control" name="Summary" >
            </div>
            
                <div class="form-group">
                <label for="">__Content___</label>
                <input type="text" value="{{\Model\pages.Content}}" class="form-control" name="Content" >
            </div>
            
                <div class="form-group">
                <label for="">__Urlimages___</label>
                <input type="text" value="{{\Model\pages.Urlimages}}" class="form-control" name="Urlimages" >
            </div>
            
                <div class="form-group">
                <label for="">__isShow___</label>
                <input type="text" value="{{\Model\pages.isShow}}" class="form-control" name="isShow" >
            </div>
            
                <div class="form-group">
                <label for="">__Type___</label>
                <input type="text" value="{{\Model\pages.Type}}" class="form-control" name="Type" >
            </div>
            
                <div class="form-group">
                <label for="">__Note___</label>
                <input type="text" value="{{\Model\pages.Note}}" class="form-control" name="Note" >
            </div>
            
                <div class="form-group">
                <label for="">__OrderBy___</label>
                <input type="text" value="{{\Model\pages.OrderBy}}" class="form-control" name="OrderBy" >
            </div>
            
                <div class="form-group">
                <label for="">__Tablename___</label>
                <input type="text" value="{{\Model\pages.Tablename}}" class="form-control" name="Tablename" >
            </div>
            
                <div class="form-group">
                <label for="">___conn___</label>
                <input type="text" value="{{\Model\pages._conn}}" class="form-control" name="_conn" >
            </div>
            
                <div class="form-group">
                <label for="">___result___</label>
                <input type="text" value="{{\Model\pages._result}}" class="form-control" name="_result" >
            </div>
            
                <div class="form-group">
                <label for="">___Query___</label>
                <input type="text" value="{{\Model\pages._Query}}" class="form-control" name="_Query" >
            </div>
            
            </form>