<div class="box box-primary">
    <div class="box-header">
        <h3 class="box-title">Nội Dung</h3>
        <div class="box-tools">
            <a href="#" class="btn btn-primary" ><i class="fa fa-plus" ></i></a>
        </div>
    </div>
    <div class="box-body">
        <form action="" enctype="multipart/form-data" method="POST" >
            <div class="form-group">
                <label for="">Trang Đặt Hàng Thành Công</label>
                <textarea type="text" class="editor" id="DatHangThanhCong" name="DatHangThanhCong" ><?php echo $data["ContentPage"] ?></textarea>
            </div>
            <button>Lưu</button>
        </form>
    </div>
</div>