<?php

use theme\dongho\functionLayout;

$functionLayout = new theme\dongho\functionLayout();
ob_start();
?>
<!DOCTYPE html>
<html lang="vi">
    <head>
        <?php
        $functionLayout->head();
        ?>
    </head>
    <body class="site " ng-cloak="TRUE" ng-app="rootApp" ng-controller="homeController" >
        <div id="body-wrapper">
            <?php
            $functionLayout->header()
            ?>
            <div class="body">
                <div class="body-content">
                    <div class="container">
                        <div class="row">
                            <?php
                            include_once $Content;
                            ?>
                        </div>
                    </div>
                </div>
            </div>

        </div>
        <?php
        $functionLayout->footer();
        ?>
    </div>
</body>
</html>
<?php
$functionLayout->DeCodeHTML();
?>