<?php
ob_start();

use theme\dongho\functionLayout;

$functionLayout = new theme\dongho\functionLayout();
?>
<!DOCTYPE html>
<html lang="vi">
    <head>
        <?php
        $functionLayout->head();
        ?>
    </head>
    <body class="site home">
        <div id="body-wrapper">
            <?php
            $functionLayout->header()
            ?>
            <div class="body">
                <?php
                include_once $Content;
                ?>
            </div>
            <?php
            $functionLayout->footer();
            ?>
        </div>
    </body>
</html>
<?php
$functionLayout->DeCodeHTML();
new functionLayout();
?>