<div class="row " ng-controller="mmenuController"  >
    <section class="col-md-3 connectedSortable" >
        <div class="box box-solid ">
            <div class="box-header bg-green-gradient">
                <i class="fa fa-list"></i>
                <h3 class="box-title">Các Menu</h3>
                <!-- tools box -->
            </div><!-- /.box-header -->
            <div class="box-body">
                <div class="box-header">
                    <div class="row">
                        <div class="input-group" style="min-width: 100px;">
                            <input type="text" ng-model="timkiemmnu" class="form-control input-sm pull-right" placeholder="Search">
                            <div class="input-group-btn">
                                <button class="btn btn-sm btn-default"><i class="fa fa-search"></i></button>
                            </div>
                        </div>
                        <div class="clearfix" ></div>
                    </div>
                </div><!-- /.box-header -->
                <div class="box-body table-responsive no-padding" style="height: 500px;" >
                    <ul class="todo-list" >
                        <li style="cursor: pointer"  ng-repeat="itemMenu in _listMenu| filter : timkiemmnu" ng-click="clickChonMenu(itemMenu.Groups)" >
                            <span class="handle">
                                <i class="fa fa-ellipsis-v"></i>
                                <i class="fa fa-ellipsis-v"></i>
                            </span>
                            <span class="text">{{itemMenu.Groups}}</span>
                        </li>
                    </ul>
                </div><!-- /.box-body -->

            </div><!-- /.box-body -->
        </div>
    </section>
    <section class="col-md-9 connectedSortable">
        <div class="box box-solid ">
            <div class="box-header bg-green-gradient">
                <i class="fa fa-calendar"></i>
                <h3 class="box-title">Menu</h3>
            </div>
            <div class="box-body ">
                <div class="col-md-3" >
                    <a href="/mmenu/addmenu/" class="btn btn-success"  >Thêm Menu</a>
                </div>
                <div class="col-md-9" >
                    <div class="input-group">
                        <input type="text" ng-model="seachModelMenus" class="form-control input-sm pull-right" placeholder="Search">
                        <div class="input-group-btn">
                            <button class="btn btn-sm btn-default"><i class="fa fa-search"></i></button>
                        </div>
                    </div>
                </div>
                <div class="col-md-12 connectedSortable" >
                    <div class="box box-solid " ng-repeat="iMenu in _listMenuByGroups| filter : seachModelMenus"   >
                        <div class="box-header bg-green-gradient">
                            <i class="fa fa-list"></i>
                            <h3 class="box-title">{{iMenu.Name}}</h3>
                        </div>
                        <div class="box-body connectedSortable" >
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <section class="col-md-12 connectedSortable" >
    </section>
</div>
