<?php
$_News = new Model\news($data["news"]);
$_Pages = new Model\pages($data["pages"]);
?>
<!-- Product -->
<div id="product">
    <div class="primary-box row">
        <h2 class="" style="padding: 10px;font-weight: bold;font-size: 20px;" ><?php echo $_News->Name ?></h2>
        <div class="col-xs-12" >
            <?php echo $_News->Content; ?>
        </div>
    </div>
</div>