<!-- ./box product RECOMMENDATION FOR YOU -->
<div style="background-color: #EFF2F8;" >

    <div class="container"  >
        <!-- blog list -->
        <div class="blog-list">
            <h2 class="page-heading text-center">
                <span class="page-heading-title">TRUECONF</span>
            </h2>
            <div class="blog-list-wapper">
                <ul class="owl-carousel" data-dots="false" data-loop="true" data-nav = "true" data-margin = "10" data-autoplayTimeout="1000" data-autoplayHoverPause = "true" data-responsive='{"0":{"items":1},"600":{"items":3},"1000":{"items":6}}'>
                    <li>
                        <div class="post-thumb image-hover2">
                            <a href="#"><img src="/public/home/assets/data/option3/blog1.jpg" alt="Blog"></a>
                        </div>
                        <div class="post-desc">
                            <h5 class="post-title">
                                <a href="#">100% Công nghệ hạ tầng thế hệ mới</a>
                            </h5>
                            <div class="post-meta">
                                <span class="date">February 27, 2015</span>
                                <span class="comment">27 comment</span>
                            </div>
                            <div class="readmore">
                                <a href="#">Readmore</a>
                            </div>
                        </div>
                    </li>
                    <li>
                        <div class="post-thumb image-hover2">
                            <a href="#"><img src="/public/home/assets/data/option3/blog2.jpg" alt="Blog"></a>
                        </div>
                        <div class="post-desc">
                            <h5 class="post-title">
                                <a href="#">Kiến trúc có thể mở rộng</a>
                            </h5>
                            <div class="readmore">
                                <a href="#">Readmore</a>
                            </div>
                        </div>
                    </li>
                    <li>
                        <div class="post-thumb image-hover2">
                            <a href="#"><img src="/public/home/assets/data/option3/blog3.jpg" alt="Blog"></a>
                        </div>
                        <div class="post-desc">
                            <h5 class="post-title">
                                <a href="#">Bảo mật thông tin</a>
                            </h5>
                            <div class="readmore">
                                <a href="#">Readmore</a>
                            </div>
                        </div>
                    </li>
                    <li>
                        <div class="post-thumb image-hover2">
                            <a href="#"><img src="/public/home/assets/data/option3/blog4.jpg" alt="Blog"></a>
                        </div>
                        <div class="post-desc">
                            <h5 class="post-title">
                                <a href="#">Chi phí bản quyền thấp</a>
                            </h5>
                            <div class="readmore">
                                <a href="#">Readmore</a>
                            </div>
                        </div>
                    </li>
                    <li>
                        <div class="post-thumb image-hover2">
                            <a href="#"><img src="/public/home/assets/data/option3/blog4.jpg" alt="Blog"></a>
                        </div>
                        <div class="post-desc">
                            <h5 class="post-title">
                                <a href="#">Chất lượng hình ảnh UltraHD</a>
                            </h5>
                            <div class="readmore">
                                <a href="#">Readmore</a>
                            </div>
                        </div>
                    </li>
                    <li>
                        <div class="post-thumb image-hover2">
                            <a href="#"><img src="/public/home/assets/data/option3/blog4.jpg" alt="Blog"></a>
                        </div>
                        <div class="post-desc">
                            <h5 class="post-title">
                                <a href="#">Sẵn sàng tích hợp đa liên kết và đa nền tảng</a>
                            </h5>
                            <div class="readmore">
                                <a href="#">Readmore</a>
                            </div>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
        <!-- ./blog list -->
    </div>
</div>
<div style="background-color: #fff;" >
    <div class="container"  >
        <!-- blog list -->
        <div class="blog-list">
            <h2 class="page-heading text-center">
                <span class="page-heading-title">CCTV</span>
            </h2>
            <div class="blog-list-wapper">
                <ul class="owl-carousel" data-dots="false" data-loop="false" data-nav = "false" data-margin = "10" data-autoplayTimeout="1000" data-autoplayHoverPause = "true" data-responsive='{"0":{"items":1},"600":{"items":3},"1000":{"items":6}}'>
                    <li>
                        <div class="post-thumb image-hover2">
                            <a href="#"><img src="/public/home/assets/data/option3/blog1.jpg" alt="Blog"></a>
                        </div>
                        <div class="post-desc">
                            <h5 class="post-title">
                                <a href="#">Người dùng máy tính Windows.</a>
                            </h5>
                            <div class="readmore">
                                <a href="#">Readmore</a>
                            </div>
                        </div>
                    </li>
                    <li>
                        <div class="post-thumb image-hover2">
                            <a href="#"><img src="/public/home/assets/data/option3/blog2.jpg" alt="Blog"></a>
                        </div>
                        <div class="post-desc">
                            <h5 class="post-title">
                                <a href="#">Người dùng iOS và watchOS.</a>
                            </h5>
                            <div class="readmore">
                                <a href="#">Readmore</a>
                            </div>
                        </div>
                    </li>
                    <li>
                        <div class="post-thumb image-hover2">
                            <a href="#"><img src="/public/home/assets/data/option3/blog3.jpg" alt="Blog"></a>
                        </div>
                        <div class="post-desc">
                            <h5 class="post-title">
                                <a href="#">Người dùng macOS và Linux.</a>
                            </h5>
                            <div class="readmore">
                                <a href="#">Readmore</a>
                            </div>
                        </div>
                    </li>
                    <li>
                        <div class="post-thumb image-hover2">
                            <a href="#"><img src="/public/home/assets/data/option3/blog4.jpg" alt="Blog"></a>
                        </div>
                        <div class="post-desc">
                            <h5 class="post-title">
                                <a href="#">Người dùng Android.</a>
                            </h5>
                            <div class="readmore">
                                <a href="#">Readmore</a>
                            </div>
                        </div>
                    </li>
                    <li>
                        <div class="post-thumb image-hover2">
                            <a href="#"><img src="/public/home/assets/data/option3/blog4.jpg" alt="Blog"></a>
                        </div>
                        <div class="post-desc">
                            <h5 class="post-title">
                                <a href="#">Người dùng trình duyệt Web.</a>
                            </h5>
                            <div class="readmore">
                                <a href="#">Readmore</a>
                            </div>
                        </div>
                    </li>
                    <li>
                        <div class="post-thumb image-hover2">
                            <a href="#"><img src="/public/home/assets/data/option3/blog4.jpg" alt="Blog"></a>
                        </div>
                        <div class="post-desc">
                            <h5 class="post-title">
                                <a href="#">Người dùng tại phòng họp.</a>
                            </h5>
                            <div class="readmore">
                                <a href="#">Readmore</a>
                            </div>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
        <!-- ./blog list -->
    </div>
</div>    

<div style="background-color: #EFF2F8;" >
    <div class="container"  >
        <!-- blog list -->
        <div class="blog-list">
            <h2 class="page-heading text-center">
                <span class="page-heading-title">Phần Mềm</span>
            </h2>
            <div class="blog-list-wapper">
                <ul class="owl-carousel" data-dots="false" data-loop="false" data-nav = "false" data-margin = "10" data-autoplayTimeout="1000" data-autoplayHoverPause = "true" data-responsive='{"0":{"items":1},"600":{"items":3},"1000":{"items":6}}'>
                    <li>
                        <div class="post-thumb image-hover2">
                            <a href="#"><img src="/public/home/assets/data/option3/blog1.jpg" alt="Blog"></a>
                        </div>
                        <div class="post-desc">
                            <h5 class="post-title">
                                <a href="#">Người dùng máy tính Windows.</a>
                            </h5>
                            <div class="readmore">
                                <a href="#">Readmore</a>
                            </div>
                        </div>
                    </li>
                    <li>
                        <div class="post-thumb image-hover2">
                            <a href="#"><img src="/public/home/assets/data/option3/blog2.jpg" alt="Blog"></a>
                        </div>
                        <div class="post-desc">
                            <h5 class="post-title">
                                <a href="#">Người dùng iOS và watchOS.</a>
                            </h5>
                            <div class="readmore">
                                <a href="#">Readmore</a>
                            </div>
                        </div>
                    </li>
                    <li>
                        <div class="post-thumb image-hover2">
                            <a href="#"><img src="/public/home/assets/data/option3/blog3.jpg" alt="Blog"></a>
                        </div>
                        <div class="post-desc">
                            <h5 class="post-title">
                                <a href="#">Người dùng macOS và Linux.</a>
                            </h5>
                            <div class="readmore">
                                <a href="#">Readmore</a>
                            </div>
                        </div>
                    </li>
                    <li>
                        <div class="post-thumb image-hover2">
                            <a href="#"><img src="/public/home/assets/data/option3/blog4.jpg" alt="Blog"></a>
                        </div>
                        <div class="post-desc">
                            <h5 class="post-title">
                                <a href="#">Người dùng Android.</a>
                            </h5>
                            <div class="readmore">
                                <a href="#">Readmore</a>
                            </div>
                        </div>
                    </li>
                    <li>
                        <div class="post-thumb image-hover2">
                            <a href="#"><img src="/public/home/assets/data/option3/blog4.jpg" alt="Blog"></a>
                        </div>
                        <div class="post-desc">
                            <h5 class="post-title">
                                <a href="#">Người dùng trình duyệt Web.</a>
                            </h5>
                            <div class="readmore">
                                <a href="#">Readmore</a>
                            </div>
                        </div>
                    </li>
                    <li>
                        <div class="post-thumb image-hover2">
                            <a href="#"><img src="/public/home/assets/data/option3/blog4.jpg" alt="Blog"></a>
                        </div>
                        <div class="post-desc">
                            <h5 class="post-title">
                                <a href="#">Người dùng tại phòng họp.</a>
                            </h5>
                            <div class="readmore">
                                <a href="#">Readmore</a>
                            </div>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
        <!-- ./blog list -->    
    </div>
</div>
<div style="background-color: #fff;" >
    <div class="container" >
        <!-- blog list -->
        <div class="blog-list">
            <h2 class="page-heading text-center">
                <span class="page-heading-title">Mạng Máy Tính</span>
            </h2>
            <div class="blog-list-wapper">
                <ul class="owl-carousel" data-dots="false" data-loop="false" data-nav = "false" data-margin = "10" data-autoplayTimeout="1000" data-autoplayHoverPause = "true" data-responsive='{"0":{"items":1},"600":{"items":3},"1000":{"items":3}}'>
                    <li>
                        <div class="post-thumb image-hover2">
                            <a href="#"><img class="img img-responsive" src="/public/home/assets/data/option3/blog1.jpg" alt="Blog"></a>
                        </div>
                        <div class="post-desc">
                            <h5 class="post-title">
                                <a href="#">Người dùng máy tính Windows.</a>
                            </h5>
                            <div class="readmore">
                                <a href="#">Readmore</a>
                            </div>
                        </div>
                    </li>
                    <li>
                        <div class="post-thumb image-hover2">
                            <a href="#"><img src="/public/home/assets/data/option3/blog2.jpg" alt="Blog"></a>
                        </div>
                        <div class="post-desc">
                            <h5 class="post-title">
                                <a href="#">Người dùng iOS và watchOS.</a>
                            </h5>
                            <div class="readmore">
                                <a href="#">Readmore</a>
                            </div>
                        </div>
                    </li>
                    <li>
                        <div class="post-thumb image-hover2">
                            <a href="#"><img src="/public/home/assets/data/option3/blog3.jpg" alt="Blog"></a>
                        </div>
                        <div class="post-desc">
                            <h5 class="post-title">
                                <a href="#">Người dùng macOS và Linux.</a>
                            </h5>
                            <div class="readmore">
                                <a href="#">Readmore</a>
                            </div>
                        </div>
                    </li>
                    <li>
                        <div class="post-thumb image-hover2">
                            <a href="#"><img src="/public/home/assets/data/option3/blog4.jpg" alt="Blog"></a>
                        </div>
                        <div class="post-desc">
                            <h5 class="post-title">
                                <a href="#">Người dùng Android.</a>
                            </h5>
                            <div class="readmore">
                                <a href="#">Readmore</a>
                            </div>
                        </div>
                    </li>
                    <li>
                        <div class="post-thumb image-hover2">
                            <a href="#"><img src="/public/home/assets/data/option3/blog4.jpg" alt="Blog"></a>
                        </div>
                        <div class="post-desc">
                            <h5 class="post-title">
                                <a href="#">Người dùng trình duyệt Web.</a>
                            </h5>
                            <div class="readmore">
                                <a href="#">Readmore</a>
                            </div>
                        </div>
                    </li>
                    <li>
                        <div class="post-thumb image-hover2">
                            <a href="#"><img src="/public/home/assets/data/option3/blog4.jpg" alt="Blog"></a>
                        </div>
                        <div class="post-desc">
                            <h5 class="post-title">
                                <a href="#">Người dùng tại phòng họp.</a>
                            </h5>
                            <div class="readmore">
                                <a href="#">Readmore</a>
                            </div>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
        <!-- ./blog list -->
    </div>    
</div>

<!-- ./box product RECOMMENDATION FOR YOU -->