<?php
$functionLayout = new theme\kcos\functionLayout();
?>
<!DOCTYPE html>
<html>
    <head>
        <?php
        $functionLayout->head();
        ?>
    </head>
    <body class="option6" ng-cloak="TRUE" ng-app="rootApp" ng-controller="homeController" >
        <?php
        $functionLayout->header();
        ?>
        <div class="columns-container"  >
            <div class="container" id="columns">
                <!-- breadcrumb -->
                <?php
                $bre = new Model\Breadcrumb();
                $bre->showBreadcrumb();
                ?>
            </div>
        </div>
        <?php
        include $Content;
//        $functionLayout->TinTucFooter();
        $functionLayout->footer();
        $functionLayout->js();
        ?>
        <script type="text/javascript" src="/public/home/assets/lib/jquery.elevatezoom.js"></script>
        <script type="text/javascript" src="/public/home/assets/lib/fancyBox/jquery.fancybox.js"></script>
    </body>
</html>

<?php 
    $functionLayout->DeCodeHTML();
?>