<div class="" ng-controller="locationController" >
    <form action="" enctype="multipart/form-data" method="POST" >
        <table class="table table-bordered" >
            <thead>
                <tr>
                    <th>#</th>
                    <th>ID</th>
                    <th>Name</th>
                    <th>Parent</th>
                    <th>Lang</th>
                    <th>Stt</th>
                </tr>
            </thead>
            <tbody>
                

            </tbody>


        </table>
        <button type="button" ng-click="savelocation()"  >lưu</button>
    </form>



</div>
