<form action="" enctype="multipart/form-data" method="POST" >
    <div class="panel ">
        <div class="panel-heading">
            <div class="btn btn-group btn-group-sm pull-right" >
                <a href="__AddLink___" class="btn btn-primary" >__langAdd___ <i class="fa fa-plus" ></i></a> 
            </div>
            <h3 class="panel-title">Thông Tin Tài Khoản</h3>
        </div>
        <div class="panel-body" >

            <textarea class="form-control" name="sql" >

            </textarea>
            <button name="btnSave" class="btn btn-success " type="submit" >Luu</button>



        </div>
    </div>    
</form>
