<?php
$a = new Model_Adapter();
$news = $data["news"];
$_new = new \Model\news($news);
?>



<div class="row " ng-controller="editnewsController" ng-init="editnewsInit('<?php echo $_new->ID ?>')" >

    <section class="col-md-12" >
        <div class="box box-solid ">
            <div class="box-header ">
                <a href="/mnews/newsbypages/<?php echo $_new->PageID ?>" class="btn btn-sm btn-primary" >
                    <i class="fa fa-arrow-left"></i>
                </a>
                <h3 class="box-title">Bài Viết</h3>
            </div>
            <div class="box-body no-padding ">

                <div >

                    <form action="" method="POST" enctype="multipart/form-data" >

                        <div class="col-md-9 " >

                            <div class="form-group">

                                <label for="">__Name___</label>

                                <input type="text" value="<?php echo $_new->Name ?>" class="form-control" name="Name" >

                            </div>



                            <div class="form-group hidden">

                                <label for="">__Alias___</label>

                                <input type="text" value="<?php echo $_new->Alias ?>" class="form-control"  name="Alias" >

                            </div>



                            <div class="form-group">

                                <label for="">__Summary___</label>

                                <textarea  class="editorMini" id="Summary" name="Summary" ><?php echo $_new->Summary ?></textarea>

                            </div>



                            <div class="form-group">

                                <label for="">__Content___</label>

                                <textarea  class="editor" id="Content" name="Content" ><?php echo $_new->Content ?></textarea>



                            </div>

                        </div>

                        <div class="col-md-3 " >

                            <div class="form-group ">

                                <label for=""></label>

                                <button type="submit" class="btn btn-success btn-block" name="EditNews" >Lưu</button>

                            </div>

                            <div class="form-group hidden">

                                <label for="">__ID___</label>

                                <input type="text" value="<?php echo $_new->ID ?>" class="form-control" name="ID" >

                            </div>

                            <div class="form-group">

                                <label for="">__PageID___</label>

                                <select name="PageID" class="form-control" >

                                    <option ng-selected="optionPage.idPa == _New.PageID" ng-repeat="optionPage in  PagesByType" value="{{optionPage.idPa}}" >{{optionPage.Name}}</option>

                                </select>

                            </div>

                            <div class="form-group">

                                <label for="">__title___</label>

                                <textarea class="form-control" name="title"  ><?php echo $_new->title ?></textarea>

                            </div>

                            <div class="form-group">

                                <label for="">__keyword___</label>

                                <textarea class="form-control" name="keyword"  ><?php echo $_new->keyword ?></textarea>

                            </div>

                            <div class="form-group">

                                <label for="">__description___</label>

                                <textarea class="form-control" name="description"  ><?php echo $_new->description ?></textarea>

                            </div>



                            <div class="form-group">

                                <label for="">__AnHien___</label>

                                <select required="required" class="form-control" ng-model="_New.AnHien"  name="AnHien" >

                                    <option value="1" >Hiện</option>

                                    <option value="0" >Ẩn</option>

                                </select>

                            </div>



                            <div class="form-group hidden">

                                <label for="">__NgayDang___</label>

                                <input type="text" value="{{_New.NgayDang}}" class="form-control" name="NgayDang" >

                            </div> 
                            <div class="form-group">
                                <div>
                                    Hình Ảnh

                                    <label
                                        style="border: 1px solid #000;background-color: rgba(0, 0, 0, 0.34);color: #fff;text-align: center;position: relative;height: 105px;display: block;z-index: 2">
                                        Chọn Hình
                                        <input style="display: none" onclick="BrowseServer('Images:/sanpham/', 'UrlHinh')"
                                               type="button" name="btnChonFile" id="btnChonFile" value="Chọn File" />
                                        <div class="HinhChon" style="position: absolute;top: 0px;z-index: 1">
                                            <img id="HinhQuanCao" src="<?php echo $_new->UrlHinh ?>"
                                                 style="height: 100px;max-width: 200px">
                                        </div>
                                    </label>
                                    <div style="clear: both"></div>
                                    <label>Hình Sản Phẩm</label>
                                    <input value="<?php echo $_new->UrlHinh ?>" type="text" class="form-control" id="UrlHinh" name="UrlHinh">

                                </div>
                            </div>

                            <div class="form-group">

                                <label for="">__TinNoiBat___</label>

                                <select required="required" class="form-control" ng-model="_New.TinNoiBat"  name="TinNoiBat" >

                                    <option value="1" >Nổi Bật</option>

                                    <option value="0" >Không Nổi Bật</option>

                                </select>

                            </div>





                            <div class="form-group">

                                <label for="">__SoLanXem___</label>

                                <input type="text" value="{{_New.SoLanXem}}" class="form-control" name="SoLanXem" >

                            </div>



                            <div class="form-group">

                                <label for="">__Stt___</label>

                                <input type="text" value="{{_New.Stt}}" class="form-control" name="Stt" >

                            </div>

                        </div>

                    </form>



                </div>

            </div><!-- /.box-body -->

        </div>

    </section>

</div>