<div class="row "  ng-controller="mpageController">
    <section class="col-md-12" >
        <div class="box box-solid ">
            <div class="box-header bg-green-gradient">
                <h3 class="box-title">Quản Lý Trang</h3>
                <!-- tools box -->
                <div class="pull-right box-tools">
                    <div class="btn-group bakco-categorymenu">
                    </div>
                    <button class="btn btn-success btn-sm" data-widget="collapse"><i class="fa fa-minus"></i></button>
                    <!--<button class="btn btn-success btn-sm" data-widget="remove"><i class="fa fa-times"></i></button>-->
                </div><!-- /. tools -->
            </div><!-- /.box-header -->
            <div class="box-body no-padding ">
                <div class="table-responsive" >
                    <a href="/pages/index/addpage/" class="btn btn-success" style="margin: 10px" >Thêm Trang</a>
                    <table class="table table-bordered" >
                        <thead>
                            <tr>
                                <th>Action</th>
                                <th>#</th>
                                <th>Tên Trang</th>
                                <th>Nhóm</th>
                                <th>Hiển Thị</th>
                                <th>Loại Trang</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr ng-repeat="itemPage in _Pages" >
                                <td style="width: 150px;" >
                                    <a class="btn btn-sm btn-primary" href="/pages/index/editpage/{{itemPage.idPa}}" >Sửa</a>
                                    <span class="bakco-modaldelete" ng-init="modaldeleteInit('Xóa', 'Thông Báo', 'Bạn có muốn xóa trang này', '/mpage/deletepage/' + itemPage.idPa, itemPage.idPa)" ></span>
                                </td>
                                <td>{{itemPage.idPa}}</td>
                                <td>
                                    <a ng-show="itemPage.Type == 1" href="/mnews/newsbypages/{{itemPage.idPa}}" >{{itemPage.Name}}</a>
                                    <a ng-show="itemPage.Type != 1" href="/mpage/editpage/{{itemPage.idPa}}" >{{itemPage.Name}}</a>
                                </td>
                                <td>{{itemPage.idGroup}}</td>
                                <td>
                                    {{itemPage.isShow==0?"Ẩn":"Hiện"}}
                                </td>
                                <td>{{itemPage.Type}}</td>
                            </tr>
                        </tbody>
                        <tfoot>
                            <tr>
                                <th>Action</th>
                                <th>#</th>
                                <th>Tên Trang</th>
                                <th>Nhóm</th>
                                <th>Hiển Thị</th>
                                <th>Loại Trang</th>
                            </tr>
                        </tfoot>

                    </table>                    
                </div>
            </div><!-- /.box-body -->
        </div>
    </section>
</div>