<?php
$_Product = $data["p"];
$a = new Model\Products();
$Img = $a->getAllImges($_Product->ID);
?>
<!-- Product -->
<div id="product">
    <div class="primary-box row">
        <div class="pb-left-column col-xs-12 col-sm-6">
            <!-- product-imge-->
            <div class="product-image">
                <div class="product-full">
                    <img onerror="this.src='/public/no-image.jpg'" id="product-zoom" src='<?php echo $Img[0] ?>' data-zoom-image="<?php echo $Img[0] ?>"/>
                </div>
                <div class="product-img-thumb" id="gallery_01">
                    <ul class="owl-carousel" data-items="3" data-nav="true" data-dots="false" data-margin="20" data-loop="true">
                        <?php
                        if ($Img)
                            foreach ($Img as $value) {
                            
                                ?> 
                                <li>
                                    <a href="#" data-image="<?php echo $value ?>" data-zoom-image="<?php echo $value ?>">
                                        <img id="product-zoom"  src="<?php echo $value ?>" /> 
                                    </a>
                                </li>
                                <?php
                            }
                        ?>

                    </ul>
                </div>
            </div>
            <!-- product-imge-->
        </div>
        <div class="pb-right-column col-xs-12 col-sm-6">
            <h1 class="product-name"><?php echo $_Product->nameProduct ?></h1>
            <div class="product-comments">
                <div class="product-star">
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star-half-o"></i>
                </div>
                <div class="comments-advices">
                    <button><i class="fa fa-pencil"></i> Sửa</button>
                </div>
            </div>
            <div class="product-price-group">
                <span class="price">{{<?php echo $_Product->Price ?>|number:0}} đ</span>
            </div>
            <div class="info-orther">
                <p>Mã Sản Phẩm: <?php echo $_Product->ID ?></p>
                <p>Tình Trạng: <span class="in-stock">Còn Hàng</span></p>
            </div>
            <div class="product-desc">
                <?php echo $_Product->Summary;
                ?>
            </div>
            <div class="form-option">
                <div class="attributes">
                    <div class="attribute-label" style="width: auto;" >Số Lượng:</div>
                    <div class="attribute-list product-qty">
                        <div class="qty">
                            <input id="option-product-qty" type="text" ng-model="qty" value="1">
                        </div>
                    </div>
                </div>
            </div>
            <div class="form-action">
                <div class="button-group">
                    <a class="btn-add-cart" href="#">Thên Giỏ Hàng</a>
                </div>
            </div>
            <div class="form-share">
                <div class="sendtofriend-print">
                    <a href="javascript:print();"><i class="fa fa-print"></i> Print</a>
                </div>
                <div class="network-share">
                    <a href="#"><i class="fa fa-facebook fa-fw"></i></a>
                    <a href="#"><i class="fa fa-google fa-fw"></i></a>
                </div>
            </div>
        </div>
    </div>
    <!-- tab product -->
    <div class="product-tab">
        <ul class="nav-tab">
            <li class="active">
                <a target="_self" aria-expanded="false" data-toggle="tab" href="#product-detail">Chi Tiết Sản Phẩm</a>
            </li>
        </ul>
        <div class="tab-container">
            <div id="product-detail" class="tab-panel active">
                <?php echo $_Product->Content ?>
            </div>
            <div id="information" class="tab-panel">
            </div>
        </div>
    </div>
    <!-- ./tab product -->
</div>
<!-- Product -->