<?php
$Model_Duser = new Module\duser\Model\Duser();
$DSOption = $Model_Duser->Admins(FALSE);
$AdminQuanTri = Module\duser\Model\Duser::CurentUsernameAdmin(TRUE);
$Error = Model\Error::getAllError();

if ($Error) {
    ?>
    <div class="col-sm-12" >
        <div style="position: fixed;top: 100px;right: 0px;width: 300px;z-index: 1999"  class="alert alert-<?php echo $Error["Type"] ?> alert-dismissible" >
            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
            <?php echo $Error["Content"]; ?>
        </div>

    </div>
    <?php
}
?>


<div class="clearfix" ></div>
<div class="">
    <div class="col-md-3">
        <div class="box box-primary">
            <div class="box-body box-profile">
                <h3 class="profile-username text-center"><?php echo $AdminQuanTri->Name ?></h3>
                <p class="text-muted text-center"><?php echo $AdminQuanTri->Groups ?></p>

                <ul class="list-group list-group-unbordered">
                    <li class="list-group-item">
                        <b>Email</b> <a class="pull-right"><?php echo $AdminQuanTri->Email ?></a>
                    </li>
                    <li class="list-group-item">
                        <b>SĐT</b> <a class="pull-right"><?php echo $AdminQuanTri->Phone ?></a>
                    </li>
                    <li class="list-group-item">
                        <b>Tài Khoản</b> <a class="pull-right"><?php echo $AdminQuanTri->Username ?></a>
                    </li>
                </ul>

            </div><!-- /.box-body -->
        </div>
    </div>
    <div class="col-md-9">
        <div class="nav-tabs-custom">
            <ul class="nav nav-tabs">
                <li class="active"><a href="#activity" data-toggle="tab">Thông Tin Chung <i class="fa fa-info-circle" ></i></a></li>
                <li  ><a href="#matkhau" data-toggle="tab">Bảo Mật <i class="fa fa-shield" ></i></a></li>

            </ul>
            <div class="tab-content">
                <div class="active tab-pane" id="activity">
                    <form method="post" action="/duser/aprofile/updateinfor/" class="form-horizontal">
                        <div class="form-group">
                            <label for="inputTaiKhoan" class="col-sm-2 control-label">Tài Khoản</label>
                            <div class="col-sm-8">
                                <input type="text" name="Username" value="<?php echo $AdminQuanTri->Username ?>" class="form-control" id="inputTaiKhoan" placeholder="Name">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputName" class="col-sm-2 control-label">Họ & Tên</label>
                            <div class="col-sm-8">
                                <input type="text" name="Name" value="<?php echo $AdminQuanTri->Name ?>" class="form-control" id="inputName" placeholder="Name">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputEmail" class="col-sm-2 control-label">Email</label>
                            <div class="col-sm-8">
                                <input type="email" name="Email" value="<?php echo $AdminQuanTri->Email ?>" class="form-control" id="inputEmail" placeholder="Email">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputName" class="col-sm-2 control-label">SĐT</label>
                            <div class="col-sm-8">
                                <input type="text" name="Phone" value="<?php echo $AdminQuanTri->Phone ?>"  class="form-control" id="inputName" placeholder="Name">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" name="SaveInfor" class="btn btn-success">Cập Nhật</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="  tab-pane" id="matkhau">
                    <form action="/duser/aprofile/updatepassword/" method="POST" class="form-horizontal">
                        <div class="form-group">
                            <label for="inputName" class="col-sm-2 control-label">Mật Khẩu Hiện Tai</label>
                            <div class="col-sm-8">
                                <input type="password" name="oldPassword" class="form-control"   placeholder="Mật khẩu">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputEmail" class="col-sm-2 control-label">Mật Khẩu Mới</label>
                            <div class="col-sm-8">
                                <input type="password" name="newPassword" class="form-control"   placeholder="Mật khẩu mật">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputName" class="col-sm-2 control-label">Nhập Lại Mật Khẩu</label>
                            <div class="col-sm-8">
                                <input type="password" name="rePassword" class="form-control"  placeholder="Nhập lại mật khẩu">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" name="SavePassword" class="btn btn-success">Cập Nhật</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <div class="clearfix" ></div>
</div>