<?php
$Produc = new Model\Products();
?>
<div class="content-page"  >
    <div class="container">
        <!-- featured category fashion -->
        <div class="category-featured fashion">
            <div class="product-featured clearfix">
                <div class="row">
                    <h3 class="text-center" style="padding: 15px;font-size: 18px;" >Sản Phẩm Mới</h3>
                    <div class="col-sm-12 col-right-tab">
                        <div class="product-featured-tab-content">
                            <ul class="product-list row"  >
                                <li class="col-sm-3"  ng-repeat="item in _Products" >
                                    <div class="right-block"  >
                                        <h5 class="product-name" style="height: 40px;" ><a href="{{item.Link}}">{{item.nameProduct}}</a></h5>
                                        <div class="content_price">
                                            <span class="price product-price">{{item.Price}}</span>
                                        </div>
                                    </div>
                                    <div class="left-block">
                                        <a href="{{item.Link}}">
                                            <img  class="lazyload img-product img-responsive" alt="{{item.nameProduct}}" data-srcset="{{item.UrlHinh}}" src="/public/images_load.gif" />
                                        </a>
                                        <div class="add-to-cart">
                                            <a title="Thêm Giỏ Hàng" href="/cart/index/addproduct/{{item.ID}}">Thêm Giỏ Hàng</a>
                                        </div>
                                    </div>
                                </li>
                            </ul>

                        </div>
                    </div>
                </div>

            </div>
        </div>

        <div class="category-featured fashion">
            <div class="product-featured clearfix">
                <div class="row">
                    <h3 class="text-center" style="padding: 15px;font-size: 18px;" >Sản Phẩm Xem Nhiều</h3>
                    <div class="col-sm-12 col-right-tab">
                        <div class="product-featured-tab-content">
                            <ul class="product-list row" >

                                <li class="col-sm-3"  ng-repeat="item in _ProductsView" >
                                    <div class="right-block"  >
                                        <h5 class="product-name" style="height: 40px;" ><a href="{{item.Link}}">{{item.nameProduct}}</a></h5>
                                        <div class="content_price">
                                            <span class="price product-price">{{item.Price}}</span>
                                        </div>
                                    </div>
                                    <div class="left-block">
                                        <a href="{{item.Link}}">
                                            <img  class="lazyload img-product img-responsive" alt="{{item.nameProduct}}" data-srcset="{{item.UrlHinh}}" src="/public/images_load.gif" />
                                        </a>
                                        <div class="add-to-cart">
                                            <a title="Thêm Giỏ Hàng" href="/cart/index/addproduct/{{item.ID}}">Thêm Giỏ Hàng</a>
                                        </div>
                                    </div>
                                </li>
                            </ul>

                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>