<?php
$view_theme = new \theme\home\functionLayout();
$_Pages = new \Model\pages($data["pages"]);
$Model_News = new \Model\news();
$newsByPage = $Model_News->NewsByPagesLimitNumber($_Pages->idPa, 9, FALSE);
?>
<!-- view-product-list-->
<div class="" >
    <div  >
        <h2  style="padding: 10px;font-weight: bold;font-size: 20px;margin-bottom: 20px;" >
            <span style="padding: 10px;border-bottom: 1px solid #0088CC;" >
                <?php echo $_Pages->Name ?>
            </span>
        </h2>
        <div id="product-detail" class="text-justify" >
            <?php echo $_Pages->Content ?>
        </div>
        <div class="clearfix" ></div>
    </div>
</div>
<!-- ./view-product-list-->
