<div class="columns-container">
    <div class="container" id="columns">
        <h2 class="page-heading no-line text-center">
            <span class="OpenSans page-heading-title2">Giỏ Hàng</span>
        </h2>
        <p class="OpenSans" >Chúng Tôi sẽ liên lạc với bạn khi bạn tạo đơn hàng</p>
        <div class="page-content page-order">
            <div class="order-detail-content">
                <table class="table table-bordered table-responsive cart_summary">
                    <thead>
                        <tr>
                            <th class="OpenSans cart_product">Hình</th>
                            <th class="OpenSans" >Mô Tả</th>
                            <th class="OpenSans" style="width: 100px;"  >Số Lượng</th>
                            <th class="OpenSans" style="width: 100px;" >Thành Tiền</th>
                            <th  class="action" style="width: 50px;"  ><a href="/cart/index/clearcart/"  ><i class="fa fa-trash-o"></i></a></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php
                        $Cart = new Module\cart\Model\Cart();
                        if ($Cart->countProduct2Cart() > 0) {
                            $Products = $Cart->Products();
                            foreach ($Products as $SanPham) {
                                $_P = new Model\Products($SanPham);
                                ?>
                                <tr>
                                    <td class="" style="width: 80px;" >
                                        <a href="<?php echo $_P->linkProduct() ?>"><img style="height: 70px;" src="<?php echo $_P->UrlHinh() ?>" alt="<?php echo $_P->nameProduct ?>"></a>
                                    </td>
                                    <td class="cart_description">
                                        <small class="cart_ref">ID : #<?php echo $_P->ID ?></small><br>
                                        <p class="product-name"><a href="<?php echo $_P->linkProduct() ?>"><?php echo $_P->nameProduct ?> </a></p>
                                        <p class="product-name"><?php echo strip_tags($_P->Summary); ?> </p>
                                        <p class="label label-success">Còn Hàng</p>
                                        <p class="label label-danger" ><?php echo $_P->Price(); ?></p>
                                    </td>
                                    <td class="qty" style="width: 100px;" >
                                        <input style="" class="inputcartnumber form-control input-sm" type="text" value="<?php echo $_P->Number ?>">
                                        <div class="btn-group-xs pull-right">
                                            <a class="btn-block btn-cart btn-primary" href="/cart/index/plusNumberProduct/<?php echo $_P->ID ?>">
                                                <i class="fa fa-caret-up"></i>
                                            </a>
                                            <a class="btn-block btn-cart btn-primary" href="/cart/index/minuNumberProduct/<?php echo $_P->ID ?>">
                                                <i class="fa fa-caret-down"></i>
                                            </a>
                                        </div>
                                    </td>
                                    <td class="price">
                                        <span><?php $ThanhTien = $_P->Price * $_P->Number; ?>
                                            <?php echo $_P->showPrice($ThanhTien); ?>
                                        </span>
                                    </td>
                                    <td class="action">
                                        <a href="/cart/index/removeproduct/<?php echo $_P->ID ?>">Delete item</a>
                                    </td>
                                </tr>
                                <?php
                            }
                        }
                        ?>


                    </tbody>
                </table>
                <div class="cart_navigation">
                    <a class="prev-btn" href="/">Tiếp Tục Mua Hàng</a>
                    <a class="next-btn" href="/cart/taodonhang">Đặt Hàng</a>
                </div>
            </div>
        </div>
    </div>
</div>