<?php
$bk = new theme\backend\backend();
$a = new Model_Adapter();
?>
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Quản trị</title>
        <!-- Tell the browser to be responsive to screen width -->
        <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
        <?php
        $bk->head();
        ?>
        <script src="/public/partials/loaderpartials/mnews/mnewsconfig.js" type="text/javascript" ></script>
    </head>
    <body class="hold-transition skin-blue-light sidebar-collapse" ng-cloak="TRUE" ng-app="rootApp"  >
        <div class="wrapper">
            <?php
            $bk->Menu();
            ?>
            <!-- Content Wrapper. Contains page content -->
            <div class="content-wrapper">
                <!-- Content Header (Page header) -->
                <?php
                $bk->Breadcrumb();
                ?>
                <!-- Main content -->
                <section class="content">
                    <?php include $Content; ?>
                </section>
            </div>
            <footer class="main-footer">
                <div class="pull-right hidden-xs">
                    <b>Version</b> 2.3.0
                </div>
                <strong>Copyright &copy; <?php echo date("Y", time()); ?> <a href="http://nguyenvando.net">bakco.com.vn</a>.</strong>
            </footer>
        </div><!-- ./wrapper -->
        <?php
        $bk->js();
        ?>
        <script src="/public/home/assets/lib/owl.carousel/owl.carousel.min.js" type="text/javascript"></script>
        <script src="/public/admin/plugins/ckeditor/ckeditor.js" type="text/javascript"></script>
        <script type="text/javascript" >
            $(document).ready(function() {
                $(".select2").select2();
                $(".owl-carousel").each(function(index, el) {
                    var config = $(this).data();
                    config.navText = ['', ''];
                    config.smartSpeed = "300";
                    if ($(this).hasClass('owl-style2')) {
                        config.animateOut = "fadeOut";
                        config.animateIn = "fadeIn";
                    }
                    $(this).owlCarousel(config);
                });
                $(".editor").each(function(index, el) {
                    CKEDITOR.replace($(this).attr("id"), {height: 500});
                });
                $(".editorMini").each(function(index, el) {
                    CKEDITOR.replace($(this).attr("id"), {
                        toolbar: [
                            {name: 'document', items: ['Source', 'Templates']},
                            ['Undo', 'Redo'],
                            {name: 'basicstyles', items: ['Bold', 'Italic']}
                        ]
                    });
                });


            });
        </script>
    </body>
</html>
