<div class="row " ng-controller="categorydetailController" ng-init="categorydetailInit(<?php echo $_Param[0] ?>)" >
    <section class="col-md-12 " >
        <div class="box box-solid ">
            <div class="box-header bg-green-gradient">
                <i class="fa fa-book"></i>
                <h3 class="box-title">Danh Mục ({{_CategoryDetail.catName}})</h3>
                <!-- tools box -->
            </div><!-- /.box-header -->
            <div class="box-body">
                <div >
                    <div class="col-md-4 connectedSortable" >
                        <div class="box box-solid " style="margin-top: 20px;" >
                            <div class="box-header bg-green-gradient">
                                <h3 class="box-title">Sửa Danh Mục </h3>
                                <!-- tools box -->
                                <div class="pull-right box-tools">
                                    <button class="btn btn-success btn-sm" data-widget="collapse"><i class="fa fa-plus"></i></button>
                                </div><!-- /. tools -->
                            </div><!-- /.box-header -->
                            <div class="box-body table-responsive" >
                                <?php
                                $a = new \Model\Error();
                                $error = $a->getError();
                                if ($error["Content"] != "") {
                                    ?> 
                                    <div class="alert alert-<?php echo $error["Type"] ?> alert-dismissible">
                                        <a href="#" class=" close" style="color: #fff;" data-dismiss="alert" aria-label="close">&times;</a>
                                        <?php echo $error["Content"] ?>
                                    </div>
                                    <?php
                                }
                                ?>
                                <div class="" ng-controller="formcategoryController" ng-init="formcategoryInit(<?php echo $_Param[0] ?>, false)" >
                                    <div ng-show="_CategoryDetail" >
                                        <form ng-show="_CategoryDetail.catID != null"   action="{{'/mcategory/edit/' + _CategoryDetail.catID}}" method="POST" enctype="multipart/form-data"  >
                                            <div class="form-group">
                                                <label >Tên Danh Mục</label>
                                                <input type="hidden" name="catID" value="{{_CategoryDetail.catID}}" >
                                                <input type="text" required="required" class="form-control" ng-model="_CategoryDetail.catName" name="catName"  placeholder="Tên Danh Mục">
                                            </div>
                                            <div class="form-group">
                                                <label >Tên Không Đấu</label>
                                                <input type="text"  class="form-control" ng-model="_CategoryDetail.Path" readonly="readonly"  placeholder="Tên Không Dấu">
                                            </div>
                                            <div class="form-group">
                                                <label >Đường Dẫn</label>
                                                <input type="text" class="form-control" ng-model="_CategoryDetail.Link" readonly="readonly" placeholder="Đường Dẫn">
                                            </div>
                                            <div class="form-group">
                                                <label >Danh Mục Cấp Trên</label>
                                                <select ng-model="_CategoryDetail.parentCatID" name="parentCatID" class="form-control select2" >
                                                    <option value="0" >Là Cấp Cha</option>
                                                    <option ng-repeat="item in ListCategory" value="{{item.catID}}" >{{item.catName}}</option>
                                                </select>
                                            </div>
                                            <div class="form-group">
                                                <label >Số Thứ Tự Tăng Dần</label>
                                                <input type="text" class="form-control" ng-model="_CategoryDetail.Serial" name="Serial"  placeholder="Số Thứ Tự Tăng Dần">
                                            </div>
                                            <div class="form-group">
                                                <label >Ghi Chú</label>
                                                <textarea name="Note" class="form-control" ng-model="_CategoryDetail.Note"   placeholder="Tên Danh Mục" ></textarea>
                                            </div>
                                            <div class="form-group">
                                                <label >
                                                    Ẩn Hiện
                                                    <input type="checkbox" name="Public" ng-checked="_CategoryDetail.Public == 1" ng-model="_CategoryDetail.Public"    >
                                                </label>
                                            </div>
                                            <div  >
                                                <button class="btn btn-success" type="submit" name="SuaDanhMuc" > Sửa</button>
                                                <a class="btn btn-danger" data-toggle="modal" target="_self" href='#modal-id'>Xóa</a>
                                                <button ng-show="showreset" class="btn btn-default" type="button"  ng-click="clickReset()" > reset</button>
                                            </div>
                                        </form>
                                        
                                        <form ng-show="_CategoryDetail.catID == null"  action="/mcategory/add/" method="POST" enctype="multipart/form-data" >
                                            <div class="form-group">
                                                <label >Tên Danh Mục</label>
                                                <input type="hidden" name="catID" value="{{_CategoryDetail.catID}}" >
                                                <input type="text" class="form-control" ng-model="_CategoryDetail.catName" name="catName"  placeholder="Tên Danh Mục">
                                            </div>
                                            <div class="form-group">
                                                <label >Danh Mục Cấp Trên</label>
                                                <select ng-model="_CategoryDetail.parentCatID" name="parentCatID" class="form-control select2" >
                                                    <option value="0" >Là Cấp Cha</option>
                                                    <option ng-repeat="item in ListCategory" value="{{item.catID}}" >{{item.catName}}</option>
                                                </select>
                                            </div>
                                            <div class="form-group">
                                                <label >Số Thứ Tự Tăng Dần</label>
                                                <input type="text" class="form-control" ng-model="_CategoryDetail.Serial" name="Serial"  placeholder="Số Thứ Tự Tăng Dần">
                                            </div>
                                            <div class="form-group">
                                                <label >Ghi Chú</label>
                                                <textarea name="Note" class="form-control" ng-model="_CategoryDetail.Note"   placeholder="Tên Danh Mục" ></textarea>
                                            </div>
                                            <div class="form-group">
                                                <label >
                                                    Ẩn Hiện
                                                    <input type="checkbox" name="Public" ng-checked="_CategoryDetail.Public == 1" ng-model="_CategoryDetail.Public"    >
                                                </label>
                                            </div>
                                            <div >
                                                <button class="btn btn-success" type="submit" name="ThemDanhMuc" > Thêm</button>
                                            </div>
                                        </form>
                                    </div>
                                    <!--form xóa-->
                                    <form action="/mcategory/delete/" enctype="multipart/form-data" method="POST" >
                                        <div class="modal fade" id="modal-id">
                                            <div class="modal-dialog">
                                                <div class="modal-content">
                                                    <div class="modal-header bg-danger">
                                                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                                                        <h4 class="modal-title">Xóa</h4>
                                                    </div>
                                                    <div class="modal-body">
                                                        <center>Nhập Mật Khẩu Để Xóa Danh Mục : {{_CategoryDetail.catName}}</center> 
                                                        <input class="form-control" type="hidden" name="catID" value="{{_CategoryDetail.catID}}" >
                                                        <input class="form-control" required="required" type="password" name="Password" placeholder="Mật khẩu của bạn" >
                                                        <p class="bg-danger" >Dang mục phải không có <b>danh mục con </b> và <b>danh mục không có sản phẩm</b>.</p>
                                                        <p class="bg-danger" >Nếu Muốn Xóa Nhiều Hãy Liên Hệ Quả Trị Viên Cao Nhất.</p>
                                                    </div>
                                                    <div class="modal-footer">
                                                        <button type="button" class="btn btn-default" data-dismiss="modal">Thoát</button>
                                                        <button type="submit" class="btn btn-success" name="xoadanhmuc" >Đồng Ý</button>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </form>
                                </div>        

                            </div><!-- /.box-body -->
                        </div>
                    </div>
                    <div class="col-md-8 connectedSortable" >
                        <div class="box box-solid " style="margin-top: 20px;" >
                            <div class="box-header bg-green-gradient">
                                <h3 class="box-title">Thông Tin Chung </h3>
                                <div class="pull-right box-tools">
                                    <button class="btn btn-success btn-sm" data-widget="collapse"><i class="fa fa-minus"></i></button>
                                </div><!-- /. tools -->
                            </div><!-- /.box-header -->
                            <div class="box-body no-padding table-responsive" >
                                <table class="table table-bordered" >
                                    <tr>
                                        <td>Mã Danh Mục</td>
                                        <td>{{_CategoryDetail.catID}}</td>
                                    </tr>
                                    <tr>
                                        <td>Tên Danh Mục</td>
                                        <td>{{_CategoryDetail.catName}}</td>
                                    </tr>
                                    <tr>
                                        <td>Danh Mục Cha</td>
                                        <td>{{_CategoryDetail.parentCatID}}</td>
                                    </tr>
                                    <tr>
                                        <td>Path</td>
                                        <td>{{_CategoryDetail.Path}}</td>
                                    </tr>
                                    <tr>
                                        <td>Link</td>
                                        <td>{{_CategoryDetail.Link}}</td>
                                    </tr>
                                    <tr>
                                        <td>Ghi Chú</td>
                                        <td>{{_CategoryDetail.Note}}</td>
                                    </tr>
                                    <tr>
                                        <td>Tình Trạng</td>
                                        <td>
                                            <small ng-show="_CategoryDetail.Public == '0'" class="label label-danger"> Ẩn</small>
                                            <small ng-show="_CategoryDetail.Public == '1'" class="label label-success"> Hiện</small>
                                        </td>
                                    </tr>

                                </table>
                                <div class="connectedSortable" ></div>
                            </div><!-- /.box-body -->
                        </div>
                        <div class="box box-solid " style="margin-top: 20px;" >

                            <div class="box-header bg-green-gradient">
                                <a ng-show="_CategoryDetail.parentCatID > 0" class="btn btn-primary btn-xs" href="/mcategory/edit/{{_CategoryDetail.parentCatID}}"  >
                                    <i class="fa fa-arrow-left" ></i>
                                </a>
                                <h3 class="box-title">Các Danh Mục Con</h3>
                                <div class="pull-right box-tools">
                                    <div class="btn-group bakco-categorymenu">
                                    </div>
                                    <button class="btn btn-success btn-sm" data-widget="collapse"><i class="fa fa-minus"></i></button>
                                </div><!-- /. tools -->
                            </div>
                            <div class="box-body no-padding table-responsive" style="height: 200px;" >
                                <table class="table table-bordered" >
                                    <thead>
                                        <tr>
                                            <th>STT</th>
                                            <th>Mã Danh Mục</th>
                                            <th>Tên Danh Mục</th>
                                            <th>Số Thứ Tự</th>
                                        </tr>
                                    </thead>

                                    <tbody>
                                        <tr ng-repeat="itemCat in _ListCategoryByParent" >
                                            <td>{{$index + 1}}</td>
                                            <td>
                                                <a href="/mcategory/edit/{{itemCat.catID}}"  ><b>{{itemCat.catID}}</b></a>
                                            </td>
                                            <td>
                                                <a href="/mcategory/edit/{{itemCat.catID}}"  ><b>{{itemCat.catName}}</b></a>
                                            </td>
                                            <td>
                                                {{itemCat.Serial}}
                                            </td>

                                        </tr>
                                    </tbody>
                                </table>

                            </div>
                        </div>

                    </div>
                </div>
            </div><!-- /.box-body -->
        </div>
    </section>
</div>