<div class="row ">
    <div class="col-md-12 ">
        <form action="/mcategory/add/" method="POST" enctype="multipart/form-data">
            <div class="box box-solid collapsed-box" style="margin-top: 20px;">

                <div class="box-header bg-green-gradient">
                    <i class="fa fa-book"></i>
                    <h3 class="box-title">Danh Mục </h3>
                    <div class="pull-right box-tools">

                        <button class="btn btn-success btn-sm" data-widget="collapse"><i class="fa fa-plus"></i></button>
                    </div>
                </div>

                <div style="display: none;" class="box-body bakco-formcategory" ng-init="formcategoryInit(_CategoryDetail.catID, true)">

                </div>
                <div class="box-footer text-right">
                    <button class="btn btn-success" type="submit" name="ThemDanhMuc">
                        Thêm</button>
                </div>
            </div>
        </form>
    </div>
    <section class="col-md-12">
        <div class="box box-solid ">
            <div class="box-header ">
                <i class="fa fa-book"></i>
                <h3 class="box-title">Danh Mục Sản Phẩm ({{ListCategory.length}})</h3>
                <div class="pull-right box-tools">
                    <a class="btn btn-primary" target="_self" data-toggle="modal" href='#modal-addForm'><i class="fa fa-plus"></i></a>

                </div><!-- /. tools -->
            </div><!-- /.box-header -->

            <div class="box-body no-padding ">

                <div class="row" ng-controller="listcategorysController">



                    <div class="col-md-12 ">
                        <table class="table ">
                            <tr>
                                <!--<th><input class="form-control" ng-model="Timkiem.catID" placeholder="Mã Danh Mục" ></th>-->

                                <th><input class="form-control" ng-model="Timkiem.catName" placeholder="Tên Danh Mục">
                                </th>

                                <th>

                                    <select ng-model="Timkiem.parentCatID" class="form-control select2">

                                        <option value="">Tất cả</option>

                                        <option ng-repeat="item in ListCategory" value="{{item.catID}}">{{item.catName}}
                                        </option>

                                    </select>



                                </th>

                            </tr>

                        </table>

                        <div class="clearfix"></div>



                        <div class="  table-responsive">
                            <table class="table table-bordered table-hover">
                                <thead>
                                    <tr>
                                        <th>STT</th>
                                        <th>Mã Danh Mục</th>
                                        <th>Tên Danh Mục</th>
                                        <th>Tên Danh Mục Cha</th>
                                        <th>Số Thứ Tự</th>
                                        <th>Ẩn Hiển</th>
                                        <th></th>
                                    </tr>
                                </thead>

                                <tbody>
                                    <tr ng-repeat="item in ListCategory| filter : Timkiem">
                                        <td>{{$index + 1}}</td>
                                        <td>
                                            <a href="/mcategory/detail/{{item.catID}}">{{item.catID}}</a>
                                        </td>

                                        <td>
                                            <a href="/mcategory/detail/{{item.catID}}"> {{item.catName}} </a>
                                        </td>
                                        <td>
                                            <a ng-show="item.parentCatID != 0" href="/mcategory/detail/{{item.parentCatID}}">{{showNameCategory(item.parentCatID)}}</a>
                                            <a ng-show="item.parentCatID == 0">{{showNameCategory(item.parentCatID)}}</a>
                                        </td>
                                        <td>{{item.Serial}}</td>
                                        <td>{{item.Public==1?"Hiện":"Ẩn"}}</td>
                                        <td>
                                            <button class="btn btn-primary" type="button" ng-click="selectCategory(item.catID)">Chọn</button>
                                        </td>
                                    </tr>
                                </tbody>
                                <tfoot>
                                    <tr>
                                        <th>Stt</th>

                                        <th>Mã Danh Mục</th>

                                        <th>Tên Danh Mục</th>

                                        <th>Tên Danh Mục Cha</th>

                                        <th>Số Thứ Tự</th>

                                        <th>Ẩn Hiển</th>

                                        <th></th>

                                    </tr>

                                </tfoot>



                            </table>

                        </div>

                    </div>

                </div>

            </div><!-- /.box-body -->

        </div>

    </section>
</div>

<form action="/mcategory/add/" method="POST" enctype="multipart/form-data">
    <div class="modal fade" id="modal-addForm">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title">Thêm Danh Mục</h4>
                </div>
                <div class="box-body  ">

                    <?php

                    use Model\Category\FornCategory;
                    use Model\FormCommon;

                    $formCat = new FornCategory();
                    $formCat->catID()->render();
                    $formCat->catName()->renderHTML();
                    $formCat->parentCatID()->renderHTML();
                    $formCat->Serial()->renderHTML();
                    $formCat->Public()->renderHTML();
                    ?>
                    <div class="d-flex">
                        <div style="width: 100%;">
                            <?php
                            $formCat->banner(null, ["id" => "banner"])->renderHTML();
                            ?>
                        </div>
                        <div style="margin-top: 25px;">
                            <?php
                            FormCommon::btnSelecImages("banner")->render();
                            ?>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button class="btn btn-success" type="submit" name="ThemDanhMuc"> Thêm</button>
                </div>
            </div>
        </div>
    </div>
</form>