<?php
$_product = new \Model\Products($data["p"]);
$Images = $_product->getAllImges($_product->ID);
?>
<div class="row" ng-controller="detailproductController"  >
    <section class="col-md-12 " >
        <div class="box box-solid ">
            <div class="box-header bg-green-gradient" >
                <div class="btn-group ">
                    <a class="btn btn-success" href="/mproduct/index/"><i class="fa fa-arrow-left" ></i></a>
                    <a class="btn btn-primary" href="/mproduct/editproduct/<?php echo $_product->ID ?>">Sửa Sản Phẩm</a>
                    <a class="btn btn-primary" target="_blank" href="<?php echo $_product->linkProduct() ?>">Xem Sản Phẩm</a>

                </div>
                <a class="btn pull-right btn-sm btn-danger" target="_self" data-toggle="modal" href='#xoasanpham<?php echo $_product->ID ?>'>Xóa</a>
                <div class="modal fade" id="xoasanpham<?php echo $_product->ID ?>">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header bg-red">
                                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                                <h4 class="modal-title">Thông báo!</h4>
                            </div>
                            <div class="modal-body">
                                <center>Bạn có muốn xóa sản phẩm này không?</center>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-default" data-dismiss="modal">Thoát</button>
                                <a href="/mproduct/deleteproduct/<?php echo $_product->ID ?>" class="btn btn-primary" >Đồng Ý</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="box-body" >
                <!-- Center colunm-->
                <div class="center_column" id="center_column">
                    <!-- Product -->
                    <div id="product">
                        <div class="primary-box row">
                            <div class="pb-left-column col-xs-12 col-sm-4">
                                <!-- product-imge-->
                                <div class="product-image">
                                    <div class="product-full">
                                        <img id="product-zoom" class="img-responsive" style="height: 400px;" src='<?php echo $_product->UrlHinh() ?>' />
                                    </div>
                                </div>
                                <!-- product-imge-->
                            </div>
                            <div class="pb-right-column col-xs-12 col-sm-8">
                                <h1 class="product-name"><?php echo $_product->nameProduct; ?></h1>
                                <div class="product-price-group">
                                    <h3 class="price"><?php echo $_product->Price() ?></h3>
                                </div>
                                <div class="info-orther">
                                    <p>Mã Sản Phẩm: <?php echo $_product->ID; ?></p>
                                </div>
                                <div class="product-desc">
                                    <?php echo $_product->Summary; ?>
                                </div>
                                <hr>
                                <div class="product-desc">
                                    <p>Danh Mục Sản Phẩm: <?php echo $_product->CatName($_product->catID); ?></p>
                                </div>
                            </div>
                        </div>
                        <!-- tab product -->
                        <div class="clearfix" ></div>
                        <div class="nav-tabs-custom" style="margin-top: 10px;">
                            <ul class="nav nav-tabs ">
                                <li class="text-center active"><a target="_self" href="#revenue-chart" data-toggle="tab">Thông tin sản phẩm</a></li>
                                <li class="text-center" ><a target="_self" href="#sales-chart" data-toggle="tab">Thương Hiệu</a></li>
                            </ul>
                            <div class="tab-content no-padding">
                                <!-- Morris chart - Sales -->
                                <div class="tab-pane active" id="revenue-chart" style="position: relative; height: 300px;overflow: auto">
                                    <?php echo $_product->Content; ?>
                                </div>
                                <div class="tab-pane" id="sales-chart" style="position: relative; height: 300px;">
                                    <?php echo $_product->ID; ?>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>

