<form action="" method="POST" enctype="multipart/form-data" > 
    <div class="form-group">
        <label for="">\Model\Products-ID</label>
        <input type="text" value="{{\Model\Products.ID}}" class="form-control" name="ID" >
    </div><div class="form-group">
        <label for="">\Model\Products-Username</label>
        <input type="text" value="{{\Model\Products.Username}}" class="form-control" name="Username" >
    </div><div class="form-group">
        <label for="">\Model\Products-catID</label>
        <input type="text" value="{{\Model\Products.catID}}" class="form-control" name="catID" >
    </div><div class="form-group">
        <label for="">\Model\Products-nameProduct</label>
        <input type="text" value="{{\Model\Products.nameProduct}}" class="form-control" name="nameProduct" >
    </div><div class="form-group">
        <label for="">\Model\Products-Price</label>
        <input type="text" value="{{\Model\Products.Price}}" class="form-control" name="Price" >
    </div><div class="form-group">
        <label for="">\Model\Products-oldPrice</label>
        <input type="text" value="{{\Model\Products.oldPrice}}" class="form-control" name="oldPrice" >
    </div><div class="form-group">
        <label for="">\Model\Products-Summary</label>
        <input type="text" value="{{\Model\Products.Summary}}" class="form-control" name="Summary" >
    </div><div class="form-group">
        <label for="">\Model\Products-Content</label>
        <input type="text" value="{{\Model\Products.Content}}" class="form-control" name="Content" >
    </div><div class="form-group">
        <label for="">\Model\Products-UrlHinh</label>
        <input type="text" value="{{\Model\Products.UrlHinh}}" class="form-control" name="UrlHinh" >
    </div><div class="form-group">
        <label for="">\Model\Products-DateCreate</label>
        <input type="text" value="{{\Model\Products.DateCreate}}" class="form-control" name="DateCreate" >
    </div><div class="form-group">
        <label for="">\Model\Products-Number</label>
        <input type="text" value="{{\Model\Products.Number}}" class="form-control" name="Number" >
    </div><div class="form-group">
        <label for="">\Model\Products-Note</label>
        <input type="text" value="{{\Model\Products.Note}}" class="form-control" name="Note" >
    </div><div class="form-group">
        <label for="">\Model\Products-BuyTimes</label>
        <input type="text" value="{{\Model\Products.BuyTimes}}" class="form-control" name="BuyTimes" >
    </div><div class="form-group">
        <label for="">\Model\Products-Views</label>
        <input type="text" value="{{\Model\Products.Views}}" class="form-control" name="Views" >
    </div><div class="form-group">
        <label for="">\Model\Products-isShow</label>
        <input type="text" value="{{\Model\Products.isShow}}" class="form-control" name="isShow" >
    </div><div class="form-group">
        <label for="">\Model\Products-lang</label>
        <input type="text" value="{{\Model\Products.lang}}" class="form-control" name="lang" >
    </div>
</form>