<?php

use lib\Common;
use Model\FormCommon;
use Model\Products;
use Model\ProductsForm;

$ProductsForm = new ProductsForm();


?>
<div class="">
    <div class="row ">
        <section class="col-md-12">
            <div class="box box-solid ">
                <div class="box-header ">
                    <a class="hidden btn btn-primary" data-toggle="modal" target="_self" href='#modal-id'>Danh Mục Sản
                        Phẩm</a>
                    <div class="box-tools">
                        <a class="btn btn-primary" href='/mproduct/addproduct/'>Thêm Sản Phẩm</a>
                    </div>
                </div>
                <div class="box-body">
                    <form method="get" action="/mproduct/index/">
                        <div class="row">
                            <div class="col-md-3">
                                <?php
                                ProductsForm::seachName($_GET["name"] ?? "", "name")->renderHTML();
                                ?>
                            </div>
                            <div class="col-md-3">
                                <?php
                                ProductsForm::catIDSeach($_GET["catID"] ?? "", "catID")->renderHTML();
                                ?>
                            </div>
                            <div class="col-md-1">
                                <?php
                                FormCommon::selectRow($_GET["PagesSize"] ?? 10, "PagesSize")->renderHTML();
                                ?>
                            </div>
                            <div class="col-md-3">
                                <br />
                                <button style="margin-top: 3px;" class="btn btn-success">Tìm Kiếm</button>
                            </div>
                        </div>
                    </form>
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th>Stt</th>
                                <th>Hinh</th>
                                <th>Tên Sản Phẩm</th>
                                <th style="width: 50px;">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php
                            if ($data["items"]) {
                                foreach ($data["items"] as $key => $value) {
                                    $_p = new Products($value);
                                    ?>
                                    <tr class="">
                                        <th style="width: 30px;">
                                            <?php echo $key + 1; ?>
                                        </th>
                                        <th style="width: 100px;">
                                            <a href="/mproduct/editproduct/<?php echo $_p->ID ?>">
                                                <div style="background-image: url('<?php echo $_p->UrlHinh() ?>');height: 70px; 
                                                background-size: 100% auto;background-repeat: no-repeat;"
                                                    class="img-bg img-7070"></div>
                                            </a>
                                        </th>
                                        <th>
                                            <div class="col-md-6">
                                                <a href="/mproduct/editproduct/<?php echo $_p->ID ?>"><?php echo $_p->nameProduct ?></a>
                                                <p>Giá: <span class="label-danger">
                                                        <?php echo $_p->Price() ?>
                                                    </span> | <span style="text-decoration: line-through; ">
                                                        <?php echo $_p->oldPrice() ?>
                                                    </span></p>
                                                <p><label class="label-warning"><i class="fa fa-eye"></i>
                                                        <?php echo $_p->Views ?>
                                                    </label></p>
                                            </div>
                                            <div class="col-md-6">
                                                <p>Ẩn Hiện:
                                                    <?php echo $_p->isShow ?>
                                                    <br>Danh Mục: <label class="label-success">
                                                        <?php echo $_p->Category()->catName; ?>
                                                    </label>
                                                </p>
                                            </div>
                                        </th>
                                        <th style="width: 180px;">
                                            <div class="btn-group " style="white-space: nowrap">
                                                <a class="btn btn-sm btn-primary"
                                                    href="/mproduct/copyproduct/<?php echo $_p->ID ?>">Copy</a>
                                                <a class="btn btn-sm btn-primary"
                                                    href="/mproduct/editproduct/<?php echo $_p->ID ?>">Sửa</a>
                                                <a onclick="return(confirm('Xóa sản phẩm này?'))" class="btn btn-sm btn-danger"
                                                    href="/mproduct/deleteproduct/<?php echo $_p->ID ?>">Xóa</a>
                                            </div>
                                        </th>
                                    </tr>

                                    <?php
                                }
                            }

                            ?>
                        </tbody>
                        <tfoot>
                            <tr>
                                <th>Stt</th>
                                <th>Hinh</th>
                                <th>Tên Sản Phẩm</th>

                                <th style="width: 50px;">Action</th>
                            </tr>
                        </tfoot>
                    </table>

                </div>
            </div>
            <?php
            echo Common::PhanTrangData($data["params"], "/mproduct/index/");
            ?>
        </section>

    </div>

</div>